CREATE TABLE IF NOT EXISTS `word` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `word` varchar(30) DEFAULT NULL,
 `x` int(11) DEFAULT NULL,
 `y` int(11) DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1
